export const TEACHER_LOGIN_REQUEST = 'TEACHER_LOGIN_REQUEST'
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS'
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL'
export const TEACHER_LOGOUT = 'TEACHER_LOGOUT'

export const TEACHER_REGISTER_REQUEST = 'TEACHER_REGISTER_REQUEST'
export const TEACHER_REGISTER_SUCCESS = 'TEACHER_REGISTER_SUCCESS'
export const TEACHER_REGISTER_FAIL = 'TEACHER_REGISTER_FAIL'